//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public string ID_Volunteer { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string ID_Country { get; set; }
        public string Gender_ID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
